services:
  - type: web
    name: LNMO_bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: "25.0.1"